### ISSUE TITLE
ignores cd option

### ISSUE THREAD

**Issue by euhruska** [olcf/wraprun#12]
Hi, I have installed wraprun on bluewaters, almost works, but in python api totally ignores cd option. It doesn't give any other errors.

**Comment by AdamSimpson** [comment]
Hi Eugen, Can you provide the wraprun command that's failing?

**Comment by euhruska** [comment]
```
from wraprun import Wraprun
dirs=['/mnt/c/scratch/sciteam/hruska/run1/run0', '/mnt/c/scratch/sciteam/hruska/run1/run1']
wraprun_options = {'pes': 1,'pes_per_node': 1, 'cd': dirs,}
run = Wraprun()
run.add_task(exe=['pwd'], **wraprun_options)
run.launch()
```

Instead the expected output, the paths in dirs, it gives only the path where it was launched from: /mnt/c/scratch/sciteam/hruska/run1

**Comment by AdamSimpson** [comment]
The working directory is changed in MPI_Init, for non MPI applications you'll need to use the serial wrapper application which is included with wraprun.

**Comment by euhruska** [comment]
How do I include the serial wrapper in python?

**Comment by mpbelhorn** [comment]
To use the serial wrapper within python, call it instead of the executable it is wrapping:

```
run.add_task(exe='pwd', **wraprun_options)
```

becomes

```
run.add_task(exe='serial pwd', **wraprun_options)
```

Of course `serial` must be added to the PATH, otherwise use the full path to the `serial` wrapper.

**Comment by euhruska** [comment]
pwd was just the test case, I want to run it with gromacs, but it fails:
Rank 0 [Fri Jul  8 15:24:01 2016] [c23-6c1s7n2] Fatal error in PMPI_Comm_size: Invalid communicator, error stack:
PMPI_Comm_size(112): MPI_Comm_size(MPI_COMM_NULL, size=0x7fffffff62dc) failed

What's the issue here?

**Comment by AdamSimpson** [comment]
Can you provide a working reproducer?

**Comment by mpbelhorn** [comment]
My guess is that either libsplit was not cross-compiled correctly for bluewaters, the wraprun environment is not setup correctly (typically prepared by an environment modulefile),  or the CrayPE environment (appropriate mpich etc) is not setup correctly. Hard to say. How was it built, using which CrayPE programming environment and what version of the CrayPE is bluewaters running?

To be fair, this tool is really meant to be installed on a Cray by the system administrators and this is the first use outside the OLCF that I'm aware of.

EDIT:
I haven't been on bluewaters in about a year and, since I am not staff there, really can't offer much advice on what should be done to use wraprun in that environment. I can only assume it's similar to our Cray XK7 which is not guaranteed.

**Comment by AdamSimpson** [comment]
No response in 8 months, closing.
